language: objective-c
osx_image: xcode7.2
env:
  global:
  - PROJECT=Demo/Demo.xcodeproj
  - IOS_SCHEME="AudioPlayer iOS"
  - OSX_SCHEME="AudioPlayer OS X"
  - TVOS_SCHEME="AudioPlayer tvOS"
  - IOS_SDK=iphonesimulator9.2
  - OSX_SDK=macosx10.11
  - TVOS_SDK=appletvsimulator9.1
  matrix:
    - DESTINATION="OS=9.0,name=iPhone 6 Plus"    SCHEME="$IOS_SCHEME"   SDK="$IOS_SDK"   RUN_TESTS="NO" BUILD_EXAMPLE="YES" POD_LINT="YES"
    - DESTINATION="OS=9.1,name=iPhone 6S"        SCHEME="$IOS_SCHEME"   SDK="$IOS_SDK"   RUN_TESTS="NO" BUILD_EXAMPLE="YES" POD_LINT="NO" 
    - DESTINATION="OS=9.2,name=iPhone 6S Plus"   SCHEME="$IOS_SCHEME"   SDK="$IOS_SDK"   RUN_TESTS="NO" BUILD_EXAMPLE="YES" POD_LINT="NO" 
    - DESTINATION="arch=x86_64"                  SCHEME="$OSX_SCHEME"   SDK="$OSX_SDK"   RUN_TESTS="NO" BUILD_EXAMPLE="YES"  POD_LINT="NO"
    - DESTINATION="OS=9.1,name=Apple TV 1080p"   SCHEME="$TVOS_SCHEME"  SDK="$TVOS_SDK"  RUN_TESTS="NO" BUILD_EXAMPLE="YES"  POD_LINT="NO"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;
    fi
  
  # Build Example in Debug if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi